name: journey2europe
description: Offline document expiration manager

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2

  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.0.3

flutter:
  uses-material-design: true
